### ISSUE TITLE
How to procure YoloV3 related file "best_1.pt" or make my own

### ISSUE THREAD

**Issue by PINTO0309** [DC1991/G2L_Net#1]
Your efforts are great!!
An error occurred when I prepared the execution environment and executed the sample script as shown below. I followed your tutorial and referred to **https://github.com/ultralytics/yolov3** but did not find the file "best_1.pt". Would you please tell me if you make it yourself or have a procurement method from somewhere?

## Executed script
```bash
$ cd demo
$ python3 test_linemod.py
```
## The error that occurred
```bash
Traceback (most recent call last):
  File "test_linemod.py", line 249, in <module>
    model, classifier, classifier_ce, classifier_box, classifier_box_gan, classifier_box_vec, pc, opt, OR,temp = load_models_yolo(obj)
  File "test_linemod.py", line 100, in load_models_yolo
    model.load_state_dict(torch.load(weights)['model'])
  File "/home/b920405/.local/lib/python3.6/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../models/1/best_1.pt'
```
## Tried with Weight download
The following Google Drive had a "404 error" and could not be referenced.
```bash
# yolov3 pytorch weights
https://drive.google.com/drive/folders/1uxgUBemJVw9wZsdpboYbzUN4bcRhsuAI
```

Thank you.

**Comment by DC1991** [comment]
I will upload the trained models soon.

**Comment by PINTO0309** [comment]
Thank you for your reply. I am looking forward to it!
