### ISSUE TITLE
About the depth image in Figure 1. 

### ISSUE THREAD

**Issue by zx19950617** [DC1991/G2L_Net#10]
Hi, @DC1991 ！Thanks for your excellent work! 
Since the depth image in the Linemod seems too dark and couln't see anything, I wonder how to visualize the depth image in Figure 1. shown as follows .
![微信图片_20201117144143](https://user-images.githubusercontent.com/38937499/99355379-1b8f5e80-28e3-11eb-87ff-61b71aca2fd6.png)

Do you pre-process the original depth image by ajusting brightness or contrast?

**Comment by DC1991** [comment]
Hi @zx19950617 , I showed the depth image by command "imshow('depth.png',[])" in MatLab.

**Comment by zx19950617** [comment]
I see, thanks for your reply!
