### ISSUE TITLE
请问如何让图片像论文中那么清晰？

### ISSUE THREAD

**Issue by tfwang96** [DC1991/G2L_Net#12]
您好，感谢您优秀的工作。
请问您是如何插入论文中的图片的呢？我尝试了一些方法但都没有您的论文中那么清晰。

**Comment by DC1991** [comment]
@tfwang96 你好，请问你具体指那些图片，我有些图片是使用 MatLab 做的，有的是在幻灯片里面做的

**Comment by tfwang96** [comment]
@DC1991 您好，我指的是例如overview中插入的图片，还有显示结果的图片。
例如下图中的：
![image](https://user-images.githubusercontent.com/33141716/113848990-9cd08a80-97cb-11eb-87d4-7d3e7ebf6428.png)
和
![image](https://user-images.githubusercontent.com/33141716/113849094-b40f7800-97cb-11eb-8cd4-7a0f663e2971.png)

**Comment by DC1991** [comment]
你好，第一幅图是直接在幻灯片内插入，保存为pdf格式，第二幅图是在原图上用opencv画的框

**Comment by tfwang96** [comment]
非常感谢！
