### ISSUE TITLE
How to understand section3.2 "Translation localization"

### ISSUE THREAD

**Issue by ShougangShen** [DC1991/G2L_Net#13]
Hello, Thank you for your work!

I'm a little confused about section3.2 Translation localization. You train a teo PointNets to perform 3D segmentation and output the residual distance ||T- T^-||. What' s the mean val T^-  of the segmented points means? Is it to calculate the mean value of these points in the camera coordinate system？ And how to understand object translation _T_ here? 

Thank you for your reply!

**Comment by DC1991** [comment]
Yeah, your understanding is right. The T^-  is the mean value of point coordinates in the camera coordinate system. The translation T is the distance between the origin of the camera coordinate system and the center of the object.

**Comment by ShougangShen** [comment]
Thanks for your reply!

In other words, is T the translation parameter in the pose parameters (R, T)? The distance between the origin of the camera coordinate system and the origin of the world system?

**Comment by DC1991** [comment]
Yeah, but the translation in this work is the distance between the origin of the camera coordinate system and the origin of the object local coordinate system.

**Comment by ShougangShen** [comment]
I'm sorry to bother you again.

In this issue #6, "The output value of R is the coordinate of 3D bounding box which is a 24D vector in the paper". I want to know if the output coordinates are in the camera coordinate system? The keypoints' number is 8, so the output is a 24D vector?  If not, what are they?  When you get the output, how to get the final R matrix?

Thanks for your reply!

**Comment by DC1991** [comment]
Yeah, the output coordinates are in the camera coordinate system. Please read our paper for the definition of the 3D bounding box and the relevant details. When getting the 24D vector, we use the Kabsch algorithm to calculate the final matrix.
