### ISSUE TITLE
Some questions about 3D sphere

### ISSUE THREAD

**Issue by jishanshanss** [DC1991/G2L_Net#14]
Thank you for your excellent work and sharing!
I'm trying to run the code and I have some questions,  Would you mind give me some explaination ?

 how to understand 'cors' in the code:  `output0, cors = model(imgs.cuda(), test=1)`, ? I find that the 'cors ' are also used in the following  : 
```
DC = int(W * cors[2][1][io] / 52)
DR = int(H * cors[2][0][io] / 52)
```
and how to undertand the 300 and 102 in the following code ?

```
dep3d = dep3d[np.where(dep3d[:, 2] > 300.0)]
dep3d = chooselimt_test(dep3d, 102, cen_depth) 
```

Hope for your reply!

**Comment by DC1991** [comment]
"cors" is the maximum position of class probability map. 'dep3d = dep3d[np.where(dep3d[:, 2] > 300.0)]' means choosing the points that more than 300 mm far away from the camera. 102 in 'dep3d = chooselimt_test(dep3d, 102, cen_depth) ' is the object(Ape) diameter (102mm).

**Comment by jishanshanss** [comment]
Thank you very much for your reply!

> "cors" is the maximum position of class probability map. 'dep3d = dep3d[np.where(dep3d[:, 2] > 300.0)]' means choosing the points that more than 300 mm far away from the camera. 102 in 'dep3d = chooselimt_test(dep3d, 102, cen_depth) ' is the object(Ape) diameter (102mm).
