### ISSUE TITLE
No model named G2L_net.

### ISSUE THREAD

**Issue by tiexuedanxin** [DC1991/G2L_Net#2]
Sorry to bother you, when I run the command of "python test_linemod.py" the following error accured, I can't find way to solve it, could you give me some advice on how to solve it, thank you for advance.

![image](https://user-images.githubusercontent.com/43425757/84511833-b44cfd00-acf9-11ea-9d05-2e4401262879.png)

**Comment by DC1991** [comment]
Hi, it seems that you are already in 'G2L_Net' file. Can you try to run the code under your 'PycharmProjects' file?

**Comment by QRayMoor** [comment]
Hi, I got the same error when I run the "**python test_linemod.py**", could you let me know how do you fix it? 
And when I run the command of "**pip install -r requirements.txt** ", the followed errors accured:

> Defaulting to user installation because normal site-packages is not writeable

> ERROR: Double requirement given: ruamel.yaml==0.15.89 (from -r requirements.txt (line 4)) (already in ruamel-yaml==0.15.46 

> (from -r requirements.txt (line 3)), name='ruamel.yaml')

Could you help? Thanks a lot!

**Comment by DC1991** [comment]
Hi QRayMoor, I have updated the requirement file. You need to run 'python test_linemod.py' outside the "G2L_Net" folder.
