### ISSUE TITLE
No /utils/render_balls_so file

### ISSUE THREAD

**Issue by GalenOOO** [DC1991/G2L_Net#3]
File "/home/galen/deepLearningCode/PoseEstimation/G2L_Net/utils/utils_funs.py", line 239, in showpoints
    dll = np.ctypeslib.load_library('../utils/render_balls_so', '.')

It seems that this file is not provided.
Can you upload this?
Thanks!

**Comment by DC1991** [comment]
Hi Thanks for your reminding, I have uploaded the missing file.
