### ISSUE TITLE
网络训练效果问题

### ISSUE THREAD

**Issue by kk-letsgo** [DC1991/G2L_Net#31]
你好，我根据你提供的物体6的训练数据集，对模型进行了训练，发现网络对旋转的预测效果不太理想。我应该怎么做才能提高准确率呢？非常感谢你的回复。

**Comment by Mahmoud-Ali-FCIS** [comment]
@kk-letsgo @DC1991 How you trained G2L?

I tried to run trained_G2l.py but i had this problem: 
RuntimeError: Given groups=1, weight of size 64 3 1 1, expected input[64, 6, 1, 1500] to have 3 channels, but got 6 channels instead

Notes that I followed all the instructions and i download the training data and put it in the right folder.
