### ISSUE TITLE
About the training process

### ISSUE THREAD

**Issue by zx19950617** [DC1991/G2L_Net#4]
Hi, @DC1991 ! Thanks for your excellent work and sharing. Now I'm confused about the training process, and I'm looking forward to your code or descriptions about the training process.

From my observation, the training contains Translation localization,  Rotation localization and others. Are these components trained jointly with the main architecture? Or trained separately? 

Any description benefits me !
Once again, thanks a lot!

**Comment by DC1991** [comment]
Hi @zx19950617 , thanks for your interest in our method. I train these three parts jointly. I will release the training code in the next few weeks. Thanks for your patience.
