### ISSUE TITLE
How to test the fps of the program？

### ISSUE THREAD

**Issue by Apollo19971206** [DC1991/G2L_Net#7]
Hello author, may I ask how to test the fps of the program？
Should it be tested on ROS or just run on the dataset?
Can you tell me the general method? I'm doing a comparative test.
Thank you!

**Comment by DC1991** [comment]
Hi, the code is only tested on the dataset: how many images are processed per second.

**Comment by Apollo19971206** [comment]
> Hi, the code is only tested on the dataset: how many images are processed per second.

Thank you very much for your answers, so FPS is the number of test pictures divided by the total test time？

**Comment by DC1991** [comment]
@Apollo19971206 Yes, sorry for late reply.
